queue_rules:
- name: default
  speculative_checks: 20
  batch_size: 20
  conditions:
  - check-success~=^commit-checks /
  - check-success~=^lint-markdown /
  - check-success~=^test

pull_request_rules:
- name: automatic rebase for dependencies
  conditions:
  - check-success~=^commit-checks /
  - check-success~=^lint-markdown /
  - check-success~=^test
  - base=main
  - author~=^dependabot(|-preview)\[bot\]$
  actions:
    queue:
      method: rebase
      rebase_fallback: merge
      name: default
