options:
  prev_tag: versio-prev

projects:
- name: changelog-action
  id: 1
  tag_prefix: ''
  labels: docker
  version:
    tags:
      default: 0.1.0
  also:
  - file: README.md
    pattern: PurpleBooth/changelog-action@v(\d+\.\d+\.\d+)
sizes:
  use_angular: true
  none: ['-', ci]
